# Generated by Django 5.2.7 on 2025-10-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='criminal_record_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='criminal_records/'),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_card',
            field=models.ImageField(blank=True, null=True, upload_to='identity_cards/'),
        ),
    ]
