# Generated by Django 5.2.7 on 2025-11-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_criminal_record_certificate_user_identity_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='criminal_record_certificate_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_card_verified',
            field=models.BooleanField(default=False),
        ),
    ]
