# Generated by Django 5.2.7 on 2025-11-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_criminal_record_certificate_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_verified',
            field=models.BooleanField(default=False),
        ),
    ]
